# .github/workflows/test-generator.yml
name: Generate Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test-generation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        # For PRs, checkout the head branch
        ref: ${{ github.event.pull_request.head.ref }}
        # For PRs from forks
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        
    - name: Generate Tests
      uses: maail/ai-mobile-test-generator@v1.0.3
      with:
        openai-api-key: ${{ secrets.OPENAI_API_KEY }}
        languages: 'swift,kotlin'
        model: 'gpt-4-turbo'

    - name: Push Changes
      run: |
        # Only attempt to push if there are changes
        if [[ -n "$(git status --porcelain)" ]]; then
          git config user.name "GitHub Test Generator Bot"
          git config user.email "<>"
          git add .
          git commit -m "Add auto-generated unit tests"
          git push
          echo "Pushed changes successfully"
        else
          echo "No changes to push"
        fi